"""add description to Todo model

Revision ID: 9550d129cf50
Revises: e0c033b04caa
Create Date: 2023-09-24 17:43:41.971150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9550d129cf50'
down_revision: Union[str, None] = 'e0c033b04caa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('todo', sa.Column('done', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'done')
    op.drop_column('todo', 'description')
    # ### end Alembic commands ###
